### PR TITLE
Fix clxv3 for Listener

### PR DESCRIPTION
**Pull request by gas2serra**
Hi Daniel,
I'm back ;)
I had a few patches in order to run the listener in CLXv3. Mainly:
>   text selection
> draw indexed pattern (images)

### CODE REVIEW

**Comment by dkochmanski** [comment]
a few ^^? Wow, thanks! :) 

I'll try to review it on Monday. I'll carry this PR to the main repository – could you make the next ones against the robert-strandth/McCLIM though? I have now access to the repository and it will be easier.

If you are interested, some issues (in main repository) are marked as bounties – if you solve them there are money rewards for solving them.

**Comment by dkochmanski** [comment]
ah, it's a major merge. I'll rebase them when reviewing against the master. I was confused for a second. Did you have some problems with merging?

**Comment by gas2serra** [comment]
I started a new branch from the Robert's master. I just add 5 commits (the last ones). Your  develop branch was just behind Robert's master. I think you will not find any problems. 

I have seen the issues marked as bounties. At the moment I'm trying to improve copy&past...
A.

**Comment by dkochmanski** [comment]
Hey, I've fixed the last commit part in the CLX:
https://github.com/sharplispers/clx/commit/7a21eb907eacdad9a61d1cc41c85da20c5ae6df3

I think we don't need to do it in McCLIM. Also I think that this size isn't calculated correctly (wrt header), it can fail with glyph size 715:

```
(ql:quickload 'clim-listener)
(defun clim-user::crash (s)
  (climi::with-text-size (t s) (princ "?")))
(clim-listener:run-listener :new-process t)

Type in clim-listener: (crash 715) – connection gets crashed.
```

**Comment by dkochmanski** [comment]
OK, I've merged whole thing except the last commit with  checking glyph size. If I'm wrong about that please correct me, then I'll also push the last commit.

**Comment by gas2serra** [comment]
Sorry, I did not see you have patched clx.

A.

**Pull request closed without merging**
