### PR TITLE
Daniel/develop

### PR DESCRIPTION
**Pull request by gas2serra**
Hi Daniel,
I moved Coordinate Swizzling into CLX backend so that "clim core" is simpler. 
I add a simpler version of "Coordinate Swizzling" for CLXv2.
It seems to me that I did not broke anything. It is a little slower. I think we need to find something better for: note-sheet-region-changed and note-sheet-transformation-changed.
At the moment they repaint all stuff:

```
  (when (and (sheet-viewable-p sheet)
	     (not (graftp sheet)))
    (dispatch-event (sheet-mirrored-ancestor sheet)
		    (make-instance 'window-repaint-event
				   :sheet (sheet-mirrored-ancestor sheet)
				   :region (sheet-native-region sheet)))))
```

That patch fixes also:
* the method-browser example in clxv2.
* the option :gadgets for mirroring in clxv2.

I found a really strange error in drei.

### CODE REVIEW

**Comment by dkochmanski** [comment]
Hey, this changes look really good :) thanks! I've tested it against clim-examples, climacs and gsharp and found no regressions.

My understanding of your changes is as follows:
- you have refactored some common functionality which doesn't depend on the specific backend from the clim-core and CLX backend into the backend called Standard (simplifying clim-core and CLX thanks to that)
- you have created CLXv3 backend
- you have fixed a few bugs

Is it correct?

Also, could you elaborate a bit about what's the difference between CLX, CLXv2 and CLXv3 and how to choose them?

**Comment by dkochmanski** [comment]
I'm closing this pull request, because I've merged it locally (and did a rebase) – so it's already in my develop – I want to avoid consecutive "Merge 'develop' to 'develop'" and "Merge 'develop' to 'master'" commits.

Great work :)

**Comment by gas2serra** [comment]
Hi,

I moved all implementation details in Standard backends. There are 3 
standard backends:

- single: when only top level sheets are mirrored (no coordinate 
swizzing) (CLXv3 backend)

- multi: when you can have mirrored and no mirrored panes (CLXv2 backend)

- full: all panes are mirrored (traditional CLX backend)

We can modify a standard backend without broke another one.

Alessandro

**Comment by gas2serra** [comment]
Robert can create its backend from single-mirrored standard backend or 
create a new standard backend.

A.

**Pull request closed without merging**
